### Correlation analysis formula:

<center> $ \rho_{i, k} = \frac{N^{11}N^{00} - N^{01}N^{10}} {\sqrt{(N^{11}+N^{10})(N^{01}+N^{00})(N^{11}+N^{01})(N^{10}+N^{00})}} $ </center>

where $ N^{11} $ and $ N^{00} $ represent the percentage of cases when both descriptors predicted correctly or incorrectly, respectively; while $ N^{10} $ and $ N^{01} $ represent cases of divergence, the first descriptor correctly predicts the class but not the second, and vice-versa, respectively; i and k refers to descriptor i and descriptor k.

In [24]:
import numpy as np

In [60]:
data_true = np.array([1, 2, 3, 4, 5])

data_cf1 = np.array([1, 2, 3, 4, 5])

data_cf2 = np.array([1, 3, 3, 4, 5])

In [67]:
d1 = data_true == data_cf1
data_true == data_cf1

array([ True,  True,  True,  True,  True])

In [68]:
d2 = data_true == data_cf2
data_true == data_cf2

array([ True, False,  True,  True,  True])

In [65]:
d1 == True

array([ True,  True,  True,  True,  True])

In [66]:
d2 == False

array([False,  True, False, False, False])

In [32]:
def compute_n10(gt, cf1, cf2):
    assert gt.shape == cf1.shape ==cf2.shape
    N = gt.shape[0]
    a1 = gt == cf1
    a2 = gt == cf2
    
    b1 = a1 == True
    b2 = a2 ==False
    
    c = sum(b1 == b2)
    
    return c/N

In [33]:
def compute_n11(gt, cf1, cf2):
    assert gt.shape == cf1.shape ==cf2.shape
    N = gt.shape[0]
    a1 = gt == cf1
    a2 = gt == cf2
    
    b1 = a1 == True
    b2 = a2 ==True
    
    c = sum(b1 == b2)
    
    return c/N

In [34]:
def compute_n00(gt, cf1, cf2):
    assert gt.shape == cf1.shape ==cf2.shape
    N = gt.shape[0]
    a1 = gt == cf1
    a2 = gt == cf2
    
    b1 = a1 == False
    b2 = a2 ==False
    
    c = sum(b1 == b2)
    
    return c/N

In [35]:
def compute_n01(gt, cf1, cf2):
    assert gt.shape == cf1.shape ==cf2.shape
    N = gt.shape[0]
    a1 = gt == cf1
    a2 = gt == cf2
    
    b1 = a1 == False
    b2 = a2 ==True
    
    c = sum(b1 == b2)
    
    return c/N

In [43]:
def correlation(gt, cf1, cf2):
    n11 = compute_n11(gt, cf1, cf2)
    n10 = compute_n10(gt, cf1, cf2)
    n00 = compute_n00(gt, cf1, cf2)
    n01 = compute_n01(gt, cf1, cf2)
    
    rho = (n11*n00-n01*n10)/(np.sqrt((n11+n10)*(n01+n00)*(n11+n01)*(n10+n00)))
    return round(rho, 3)

In [77]:
data_true = np.array([1, 2, 3, 4, 5])

data_cf1 = np.array([1, 2, 3, 4, 5])

data_cf2 = np.array([1, 4, 8, 2, 1])

In [78]:
correlation(data_true, data_cf1, data_cf2)

-0.6